// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YCHET_AUTOSTOYANKI.Tables;

#nullable disable

namespace YCHET_AUTOSTOYANKI.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autoname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Autos");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Autostop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seats")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Autostops");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutosId")
                        .HasColumnType("integer");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gosnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Midname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numberphone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<string>("SeriaNumberDoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AutosId");

                    b.HasIndex("RolesId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutostopsId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ConclusionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StaffsId")
                        .HasColumnType("integer");

                    b.Property<int>("VouchersId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutostopsId");

                    b.HasIndex("ClientsId");

                    b.HasIndex("StaffsId");

                    b.HasIndex("VouchersId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Sale")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Namerole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Desription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Midname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Indate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Outdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Summ")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscountsId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Client", b =>
                {
                    b.HasOne("YCHET_AUTOSTOYANKI.Tables.Auto", "Autos")
                        .WithMany()
                        .HasForeignKey("AutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YCHET_AUTOSTOYANKI.Tables.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autos");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Contract", b =>
                {
                    b.HasOne("YCHET_AUTOSTOYANKI.Tables.Autostop", "Autostops")
                        .WithMany()
                        .HasForeignKey("AutostopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YCHET_AUTOSTOYANKI.Tables.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YCHET_AUTOSTOYANKI.Tables.Staff", "Staffs")
                        .WithMany()
                        .HasForeignKey("StaffsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YCHET_AUTOSTOYANKI.Tables.Voucher", "Vouchers")
                        .WithMany()
                        .HasForeignKey("VouchersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autostops");

                    b.Navigation("Clients");

                    b.Navigation("Staffs");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Staff", b =>
                {
                    b.HasOne("YCHET_AUTOSTOYANKI.Tables.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("YCHET_AUTOSTOYANKI.Tables.Voucher", b =>
                {
                    b.HasOne("YCHET_AUTOSTOYANKI.Tables.Discount", "Discounts")
                        .WithMany()
                        .HasForeignKey("DiscountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discounts");
                });
#pragma warning restore 612, 618
        }
    }
}
